### ISSUE TITLE
Divided by zero Exception

### ISSUE THREAD

**Issue by Daniele-Cattabriga** [IngSW-unipv/AlchemicalBank#2]
Le classi Francioli472317 e AimanAlMasoud472462 lanciano un'eccezione aritmetica divided by zero su alte iterazioni, per riferimento ho impostato gli anni a 1000, e ogni esecuzione causava l'eccezione.
L'output è questo:

Exception in thread "main" java.lang.ArithmeticException: / by zero
	at it.unipv.ingsw.alchemicalbank.wizards.Francioli471642.askKeepOrLiquidate(Francioli471642.java:41)
	at it.unipv.ingsw.alchemicalbank.wizards.AimanAlMasoud472462.askKeepOrLiquidate(AimanAlMasoud472462.java:168)
	at it.unipv.ingsw.alchemicalbank.InvestmentFund.nextMonth(InvestmentFund.java:53)
	at it.unipv.ingsw.alchemicalbank.Bank.manageFund(Bank.java:87)
	at it.unipv.ingsw.alchemicalbank.Bank.simulateYear(Bank.java:76)
	at it.unipv.ingsw.alchemicalbank.Bank.runSimulation(Bank.java:64)
	at it.unipv.ingsw.alchemicalbank.AlchemicalBank.main(AlchemicalBank.java:31)

@aiman-al-masoud
Francioli non so l'handle, se qualcuno può contattarlo per favore.

**Comment by aiman-al-masoud** [comment]
aggiustato dal mio lato, era colpa mia.

**Comment by Daniele-Cattabriga** [comment]
ok funziona grazie!
